default_context:
  project_name: 'harena-logger'
  project_slug: 'harena-logger'
  domain_main: 'harenaloggerurl.com'
  domain_staging: 'stag.harenaloggerurl.com'
  docker_swarm_stack_name_main: 'harenaloggerurl-com'
  docker_swarm_stack_name_staging: 'stag-harenaloggerurl-com'
  secret_key: '1bf8c31d9cc5ffec1772b6e279eb595d65164861293aad6b543a72957d2de68b'
  first_superuser: 'logger'
  first_superuser_password: 'harena'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.harenaloggerurl.com", "https://stag.harenaloggerurl.com", "https://harenaloggerurl.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@harenaloggerurl.com'
  postgres_password: 'harena'
  pgadmin_default_user: 'logger'
  pgadmin_default_user_password: 'harena'
  traefik_constraint_tag: 'harenaloggerurl.com'
  traefik_constraint_tag_staging: 'stag.harenaloggerurl.com'
  traefik_public_constraint_tag: 'HARENA_LOGGER_TRAEFIK'
  flower_auth: 'logger:harena'
  sentry_dsn: 'https://4545043b2c46405bafd287ca4773b277@o1000618.ingest.sentry.io/5960001'
  docker_image_prefix: 'harena-logger-'
  docker_image_backend: 'harena-logger-backend'
  docker_image_celeryworker: 'harena-logger-celeryworker'
  docker_image_frontend: 'harena-logger-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
