version: "3.3"
services:

  proxy:
    image: traefik:v2.2
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
#      # Listen on port 443, default for HTTPS
#      - target: 443
#        published: 443
#        mode: host
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `${TRAEFIK_TAG?Variable not set}`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
#      - --api
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK?Variable not set}
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        - traefik.constraint-label=${TRAEFIK_PUBLIC_TAG?Variable not set}
        # traefik-http set up only to use the middleware to redirect to https
#        - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.scheme=https
#        - traefik.http.middlewares.${STACK_NAME?Variable not set}-https-redirect.redirectscheme.permanent=true
        # Handle host with and without "www" to redirect to only one of them
        # Uses environment variable DOMAIN
        # To disable www redirection remove the Host() you want to discard, here and
        # below for HTTPS
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.entrypoints=http
        # traefik-https the actual router using HTTPS
#        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.rule=Host(`${DOMAIN?Variable not set}`) || Host(`www.${DOMAIN?Variable not set}`)
#        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.entrypoints=https
#        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
#        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.tls.certresolver=le
        # Define the port inside of the Docker service to use
        - traefik.http.services.${STACK_NAME?Variable not set}-proxy.loadbalancer.server.port=80
        # Handle domain with and without "www" to redirect to only one
        # To disable www redirection remove the next line
#        - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.regex=^http?://(www.)?(${DOMAIN?Variable not set})/(.*)
        # Redirect a domain with www to non-www
        # To disable it remove the next line
#        - traefik.http.middlewares.${STACK_NAME?Variable not set}-www-redirect.redirectregex.replacement=https://${DOMAIN?Variable not set}/$${3}
        # Redirect a domain without www to www
        # To enable it remove the previous line and uncomment the next
        # - traefik.http.middlewares.${STACK_NAME}-www-redirect.redirectregex.replacement=https://www.${DOMAIN}/$${3}
        # Middleware to redirect www, to disable it remove the next line
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-https.middlewares=${STACK_NAME?Variable not set}-www-redirect
        # Middleware to redirect www, and redirect HTTP to HTTPS
        # to disable www redirection remove the section: ${STACK_NAME?Variable not set}-www-redirect,
        - traefik.http.routers.${STACK_NAME?Variable not set}-proxy-http.middlewares=${STACK_NAME?Variable not set}-www-redirect,${STACK_NAME?Variable not set}-https-redirect

  zookeeper:
    image: bitnami/zookeeper
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  brokerkafka:
    image: bitnami/kafka
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    depends_on:
      - brokerkafka
    env_file:
      - .env
    deploy:
      labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
      - traefik.http.routers.${STACK_NAME?Variable not set}-kafdrop.rule=Host(`kafdrop.${DOMAIN?Variable not set}`)
      - traefik.http.services.${STACK_NAME?Variable not set}-kafdrop.loadbalancer.server.port=9000
      - traefik.http.routers.${STACK_NAME?Variable not set}-kafdrop.middlewares=${STACK_NAME?Variable not set}-kafdrop-basicauth
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-kafdrop-basicauth.basicauth.removeheader=true
      - traefik.http.middlewares.${STACK_NAME?Variable not set}-kafdrop-basicauth.basicauth.users=${TRAEFIK_USERS?Variable not set}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD?Variable not set}
    volumes:
      - elastic-db-data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.elastic-db-data == true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
#    ports:
#      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://${ELASTICSEARCH_SERVER?Variable not set}:9200
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME?Variable not set}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD?Variable not set}
    deploy:
      labels:
        #        - traefik.enable=true
        #        - traefik.constraint-label=${TRAEFIK_TAG?Variable not set}
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-http.entrypoints=http
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-http.middlewares=${STACK_NAME?Variable not set}-https-redirect
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-https.rule=Host(`mongoexpress.${DOMAIN?Variable not set}`)
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-https.entrypoints=https
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-https.tls=true
        #        - traefik.http.routers.${STACK_NAME?Variable not set}-mongoexpress-https.tls.certresolver=le
        #        - traefik.http.services.${STACK_NAME?Variable not set}-mongoexpress.loadbalancer.server.port=8081
        - traefik.enable=true
        - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
        - traefik.http.routers.${STACK_NAME?Variable not set}-kibana.rule=Host(`kibana.${DOMAIN?Variable not set}`)
        - traefik.http.services.${STACK_NAME?Variable not set}-kibana.loadbalancer.server.port=5601
        - traefik.http.routers.${STACK_NAME?Variable not set}-kibana.middlewares=${STACK_NAME?Variable not set}-kibana-basicauth
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-kibana-basicauth.basicauth.removeheader=true
        - traefik.http.middlewares.${STACK_NAME?Variable not set}-kibana-basicauth.basicauth.users=${TRAEFIK_USERS?Variable not set}
    depends_on:
      - elasticsearch



  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.${STACK_NAME?Variable not set}.app-db-data == true
  
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - brokerkafka
      - mongo
    env_file:
      - .env
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label-stack=${TRAEFIK_TAG?Variable not set}
        - traefik.http.routers.${STACK_NAME?Variable not set}-backend-http.rule=PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`)
        - traefik.http.services.${STACK_NAME?Variable not set}-backend.loadbalancer.server.port=80
  
  actionworker:
    image: '${DOCKER_IMAGE_ACTIONWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - brokerkafka
      - mongo
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST?Variable not set}
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    build:
      context: ./backend
      dockerfile: systemworker.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  systemworker:
    image: '${DOCKER_IMAGE_SYSTEMWORKER?Variable not set}:${TAG-latest}'
    depends_on:
      - db
      - brokerkafka
      - mongo
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST?Variable not set}
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    build:
      context: ./backend
      dockerfile: actionworker.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}


volumes:
  app-db-data:
  elastic-db-data:
networks:
  traefik-public:
    # Allow setting it to false for testing
    external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
