[tool.poetry]
name = "harena-logger"
version = "0.1.0"
description = ""
authors = ["Victor S. <victorsaez@stoom.com.br>"]

[tool.poetry.dependencies]
python = "^3.8.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
